# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee3f0807249f2935e17844aee4da215ef1e8caaeebecb696bc356ba6b71dd1192ac0b8828c7a15da6977b46b937d0602aa39d72652ec589ecf12b07ae62ac2c7

test:
  secret_key_base: f225729b58ce981ad3358f12590420af9d9e132f2d4055e1303523c6fdde6798216c05008fcb29e47028ff81189cb483e19507f4cb99a6923479f876152f0a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
